"""python -m cesm_fields CESM_CHECKOUT OUT_DIR

Writes OUT_DIR/<component>.yaml for atm, lnd, ice, ocn, glc, rof.
"""

import os
import sys
from pathlib import Path

import yaml

from .components import cam, cice, cism, ctsm, mom6, mosart

HEADER = """\
# GENERATED by cesm-field-scraper from {tag}. Regenerate, don't edit.
#
# One record per registration call site. `dims` excludes time (see `time`)
# and the horizontal dims (see `horizontal`). A record with `name_expr` had
# its name built at runtime: with a `name` it's an expansion of that
# expression, with `name: null` it couldn't be resolved (`name_patterns`
# holds whatever the source does fix).

"""


class Dumper(yaml.SafeDumper):
    pass


# Lists of strings (dims, patterns) on one line.
Dumper.add_representer(list, lambda d, data: d.represent_sequence(
    "tag:yaml.org,2002:seq", data, flow_style=all(isinstance(x, str) for x in data)))


def main(cesm, out):
    tag = os.environ.get("CESM_TAG", "an unpinned checkout")
    Path(out).mkdir(parents=True, exist_ok=True)
    for c in [cam, ctsm, cice, mom6, cism, mosart]:
        fields = sorted(c.scrape(Path(cesm) / c.REPO_PATH),
                        key=lambda r: (r["name"] is None, r["name"] or r["name_expr"], r["source"]))
        names = {r["name"] for r in fields if r["name"]}
        summary = {"records": len(fields), "distinct_names": len(names),
                   "unresolved_names": sum(r["name"] is None for r in fields)}
        doc = {"component": c.COMPONENT, "model": c.MODEL, "cesm_tag": tag,
               "horizontal": c.HORIZONTAL, "summary": summary, "fields": fields}
        with open(Path(out) / f"{c.COMPONENT}.yaml", "w") as f:
            f.write(HEADER.format(tag=tag))
            yaml.dump(doc, f, Dumper=Dumper, sort_keys=False, width=1000)
        print(c.COMPONENT, c.MODEL, summary)


if __name__ == "__main__":
    main(*sys.argv[1:])
